name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ${{ secrets.DOCKER_USER }}
  IMAGE_NAME: ${{ secrets.DOCKER_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: "Create env file"
        run: |
          touch .env
          echo REACT_APP_BASE_URL="https://pos-backend.suttipongact.com/" >> .env
          cat .env
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME) --tag ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
      - name: Docker push with tag
        run: docker push ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME)
